### ISSUE TITLE
Bit more information in `First steps` docs

### ISSUE THREAD

**Issue by k0nG** [wagtail/wagtail-wordpress-import#116]
In the README.md under [First steps to configure your wagtail app](https://github.com/torchbox/wagtail-wordpress-import#first-steps-to-configure-your-wagtail-app), the documentation could be a bit more specific about where to put the example model. This is mentioned later, so maybe a change in ordering.

Also some more background about how the `import_wordpress_data` method works would be helpful.

**Comment by nickmoreton** [comment]
> Also some more background about how the import_wordpress_data method works would be helpful.

**Question**: Hi Matt, is this what you where looking for: https://github.com/torchbox/wagtail-wordpress-import/blob/main/docs/import_process.md
