### ISSUE TITLE
Category plugin crashes if the category is an integer

### ISSUE THREAD

**Issue by fabienheureux** [wagtail/wagtail-wordpress-import#148]
I have a situation where the category is an interger (a year in this case, `2016` for example).

This causes this line to crash : https://github.com/torchbox/wagtail-wordpress-import/blob/41c8ef9623e0796a2362befc416500e4e6550a3a/wagtail_wordpress_import/importers/wordpress.py#L309

Adding a `len(str(category))` could prevent this.  
I will try to submit a PR next week.

**Comment by nickmoreton** [comment]
I'll boot this up: https://github.com/nickmoreton/wwi-docker-develop and try it out. 😄
