### ISSUE TITLE
Listing on Django packages

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail-wordpress-import#149]
* https://djangopackages.org/grids/g/wagtail-migration/
* Would be good to have this package listed there, and this would populate the migrations entry on https://wagtail.io/packages/

**Comment by nimasmi** [comment]
Thanks @lb- for the suggestion. I have added it at https://djangopackages.org/packages/p/wagtail-wordpress-import/. It's not yet in the grid you linked to, though I have added it there too. I'm guessing cacheing is involved. Ditto at https://wagtail.org/packages/#wagtail-migration

**Comment by nimasmi** [comment]
Django Packages only took an hour or so yesterday to update. Wagtail.org is now updated. I'm closing this issue. Thanks again @lb-.

**Comment by lb-** [comment]
awesome
