### ISSUE TITLE
Don't duplicate matrix in github actions file

### ISSUE THREAD

**Issue by fabienheureux** [wagtail/wagtail-wordpress-import#153]
Following this comment https://github.com/torchbox/wagtail-wordpress-import/pull/152#issuecomment-1033695514 

I would like to suggest using a more synthetic approach to the way the matrix is written in https://github.com/torchbox/wagtail-wordpress-import/blob/main/.github/workflows/test.yml#L17-L20

We can easily use a json file in order to specify the versions, based on this example : https://github.com/nobe4/test-action-matrix
Let me know what you think of this approach, I would be happy to implement it :+1:

**Comment by nickmoreton** [comment]
Closing as this was merged
